---
- name: Config hostname
  ansible.builtin.template:
    src: /root/playbooks/roles/kubeadm/templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Stop service firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
