infra_ip:
  - 10.0.2.15

node_selector:
  label: node-role.kubernetes.io/master

tolerations:
  key: node-role.kubernetes.io/master
  operator: Exists
  value: reserved
  effect: NoSchedule

istioBinaryPath:
  path: /root/istio-1.14.1/bin/istioctl

download_path: /root
