---
- name: Download_helm
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz
    dest: /root
    mode: '0644'

- name: Get_installer
  ansible.builtin.shell: |
    tar xvf helm-v3.9.3-linux-amd64.tar.gz
    mv linux-amd64/helm /usr/local/bin
    rm -rf linux-amd64
  changed_when: true

- name: Move_binary
  ansible.builtin.command: helm version
  register: helm_v
  changed_when: true

- name: Display_helm
  ansible.builtin.debug:
    var: helm_v
