- name: Disable_firewall
  ansible.builtin.service:
    name: firewalld
    state: stopped

- name: Close_swap
  ansible.builtin.command: swapoff -a
  changed_when: true

- name: Config_module_containerd
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: '0644'

- name: Modprobe_overlay
  ansible.builtin.command: sudo modprobe overlay
  changed_when: true

- name: Modprobe_br_netfilter
  ansible.builtin.command: sudo modprobe br_netfilter
  changed_when: true

- name: Config_sysctl
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'

- name: Apply
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Apply_sysctl
  ansible.builtin.shell: sudo sysctl --system && sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
  changed_when: true
  register: value

- name: Display_log
  ansible.builtin.debug:
    var: value

- name: Yum_download_utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Yum_download_repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
    mode: '0644'

- name: Enable repo
  ansible.builtin.command: yum-config-manager --enable \*
  changed_when: true

- name: Yum_Update
  ansible.builtin.yum:
    update_cache: true

- name: Containerd_download
  ansible.builtin.yum:
    name: containerd
    state: present

- name: Config_cgroup
  ansible.builtin.copy:
    content: |
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Enable containerd
  ansible.builtin.service:
    name: containerd
    enabled: true
